
services:
  oracle-db:
    image: container-registry.oracle.com/database/enterprise:19.3.0.0
    container_name: oracle19
    environment:
    - ORACLE_SID=orcdc
    - ORACLE_PDB=orcl
    - ORACLE_PWD=password
    - INIT_SGA_SIZE=3000
    - INIT_PGA_SIZE=1000
    - ENABLE_ARCHIVELOG=true
    - ENABLE_FORCE_LOGGING=true
    shm_size: '4g'
    ports:
    - 11521:1521
    - 55500:5500
    volumes:
    - /opt/oracle/oradata
