services:
  postgresql:
    container_name: postgres
    image: 'postgres:${PG_VERSION}'
    environment:
      - 'POSTGRES_USER=${PG_USER}'
      - 'POSTGRES_PASSWORD=${PG_PASSWORD}'
      - 'POSTGRES_DB=${PG_DB}'
    ports:
      - '5432:5432'
    networks:
      - db.net
    volumes:
      - 'postgres-bin:/usr/lib/postgresql/${PG_VERSION}/bin'
      - 'postgres-data:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD", "sh -c 'pg_isready -U ${PG_USER} -d ${PG_DB}'"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres-bin:
  postgres-data:

networks:
  db.net:
    name: the-db-collection
    external: true
